export enum CloseCodes {
	UnknownError = 4000,
	UnknownOPCode,
	DecodeError,
	NotAuthenticated,
	AuthenticationFailed,
	AlreadyAuthenticated,
	InvalidSeq = 4007,
	RateLimited,
	SessionTimedOut,
	InvalidShard,
	ShardingRequired,
	InvalidAPIVersion,
	InvalidIntents,
	DisallowedIntents
}

export enum JSONErrorCodes {
	General,
	UnknownAccount = 10001,
	UnknownApplication,
	UnknownChannel,
	UnknownGuild,
	UnknownIntegration,
	UnknownInvite,
	UnknownMember,
	UnknownMessage,
	UnknownPermissionOverwrite,
	UnknownProvider,
	UnknownRole,
	UnknownToken,
	UnknownUser,
	UnknownEmoji,
	UnknownWebhook,
	UnknownBan = 10026,
	UnknownSKU,
	UnknownStoreListing,
	UnknownEntitlement,
	UnknownBuild,
	UnknownLobby,
	UnknownBranch,
	UnknownRedistributable = 10036,
	UnknownGuildTemplate = 10057,
	UnknownInteraction = 10062,
	ForbiddenBotEndpoint = 20001,
	BotOnlyEndpoint,
	AnnouncementRateLimit = 200022,
	ChannelRateLimit = 200028,
	MaximumGuildsReached = 30001,
	MaximumFriendsReached,
	MaximumPinsReached,
	MaximumRolesReached = 30005,
	MaximumWebhooksReached = 30007,
	MaximumReactionsReached = 30010,
	MaximumChannelsReached = 30013,
	MaximumAttachmentsReached = 30015,
	MaximumInvitesReached,
	GuildTemplateExists = 30031,
	Unauthorized = 40001,
	VerifiedAccountRequired,
	MaximumRequestSizeReached = 40005,
	FeatureTemporarilyDisabled,
	BannedUser,
	MessageAlreadyCrossposted = 40033,
	MissingAccess = 50001,
	InvalidAccountType,
	BlockedDMExecution,
	WidgetDisabled,
	InvalidMessageAuthor,
	EmptyMessage,
	BlockedDMSend,
	BlockedVoiceChannelSend,
	InvalidVerificationLevel,
	MissingOAuthApplicationBot,
	MaximumOAuthApplicationReached,
	InvalidOAuthState,
	InvalidPermissions,
	InvalidAuthenticationToken,
	MaximumNoteLengthReached,
	InvalidMessageDeleteAmount,
	InvalidChannelPin = 50019,
	InvalidInviteCode,
	BlockedSystemMessageExecution,
	BlockedChannelTypeExecution = 50024,
	InvalidOAuthToken,
	InvalidWebhookToen = 50027,
	InvalidRecipients = 50033,
	MaximumBulkDeleteAgeReached,
	InvalidFormBody,
	InvalidAcceptedBotInvite,
	InvalidAPIVersion = 50041,
	RequiredCommunityChannel = 50074,
	InvalidStickerSent = 50081,
	ReactionBlocked = 90001,
	APIOverloaded = 130000
}

export enum OPCodes {
	Dispatch,
	Heartbeat,
	Identify,
	StatusUpdate,
	VoiceStateUpdate,
	VoiceGuildPing,
	Resume,
	Reconnect,
	RequestGuildMembers,
	InvalidSession,
	Hello,
	HeartbeatAck
}

export enum RPCCloseCodes {
	InvalidClientID = 4000,
	InvalidOrigin,
	RateLimited,
	TokenRevoked,
	InvalidVersion,
	InvalidEncoding
}

export enum RPCCodes {
	UnknownError = 1000,
	InvalidPayload = 4000,
	InvalidCommand = 4002,
	InvalidGuild,
	InvalidEvent,
	InvalidChannel,
	InvalidPermissions,
	InvalidClientID,
	InvalidOrigin,
	InvalidToken,
	InvalidUser,
	OAuth2Error = 5000,
	SelectChannelTimedOut,
	GetGuildTimedOut,
	SelectVoiceForceRequired,
	CaptureShotcutAlreadyListening
}

export enum VoiceCloseCodes {
	UnknownOPCode = 4001,
	NotAuthenticated = 4003,
	AuthenticationFailed,
	AlreadyAuthenticated,
	InvalidSession,
	SessionTimeout = 4009,
	ServerNotFound = 4011,
	UnknownProtocol = 4012,
	Disconnected = 4014,
	VoiceServerCrashed,
	UnknownEncryptionMode
}

export enum VoiceOPCodes {
	Identify,
	SelectProtocol,
	Ready,
	Heartbeat,
	SessionDescription,
	Speaking,
	HeartbeatAck,
	Resume,
	Hello,
	Resumed,
	ClientDisconnect = 13
}
