version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: extended-utility-types
    versions:
    - 1.10.1
    - 1.12.0
    - 1.14.0
    - 1.15.0
    - 1.16.0
    - 1.9.0
  - dependency-name: "@microsoft/tsdoc-config"
    versions:
    - 0.15.2
  - dependency-name: eslint-plugin-tsdoc
    versions:
    - 0.2.14
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.20.0
    - 4.22.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.20.0
    - 4.22.0
  - dependency-name: eslint
    versions:
    - 7.23.0
